// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace TaxiFarePredictionAppML.Model
{
    public class TaxiFarePrediction
    {
        public float Score { get; set; }
    }
}
